TASKS_SAVE_NAME = "tasks_save1"
SCREENS_SAVE_NAME = "screens_save1"
SAVE_FOLDER = "./saves"
TASKS_SAVE_PATH = f"{SAVE_FOLDER}/{TASKS_SAVE_NAME}.json"
SCREENS_SAVE_PATH = f"{SAVE_FOLDER}/{SCREENS_SAVE_NAME}.json"
TASK_BUTTON_DEFAULT_COLOR = [1, 1, 1]
TASK_BUTTON_ACTIVE_COLOR_DELTA = 0.3
